services:
# Database container
  db:
    image: postgres:16.1
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      retries: 5
      start_period: 30s
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    command: >
      -c ssl=on
      -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
      -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
    # expose:
    #   - 5432
    ports:
      - 5432:5432
      - 55432:55432
    networks:
      - regos
    volumes: 
      - db:/var/lib/postgresql/data 
# Core API container
  admin-api:
    image: "geapex/domain-os:${BRANCH}"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/ping || exit"]
      interval: 3s
      retries: 5
      start_period: 10s
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ENV=${ENV}
      - GIN_MODE=${GIN_MODE}
      - OPENEXCHANGERATES_APP_ID=${OPENEXCHANGERATES_APP_ID}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - API_PORT=${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - regos
# TEST container from wich we will be running integration tests based on a postman collection
  test:
    image: postman/newman
    command:
      run "https://api.getpostman.com/collections/"${POSTMAN_COLLECTION_ID}"?apikey="${POSTMAN_API_KEY} -e "https://api.getpostman.com/environments/"${POSTMAN_ENVIRONMENT_ID}"?apikey="${POSTMAN_API_KEY} 
    environment:
      - apikey=${POSTMAN_API_KEY}
      - collection=${POSTMAN_COLLECTION_ID}
      - environment=${POSTMAN_ENVIRONMENT_ID}
    depends_on:
      admin-api:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - regos  

networks:
  regos:
    driver: bridge

volumes:
  db:
    driver: local