apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: domain-os-dev
build:
  local:
    push: false
  artifacts:
    - image: gprins/domain-os
      context: .
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'internal/**/*.go'
            dest: .
          - src: 'cmd/api/**/*.go'
            dest: .
    - image: gprins/unified-worker
      context: .
      docker:
        dockerfile: cmd/workers/unified/Dockerfile
      sync:
        manual:
          - src: 'internal/**/*.go'
            dest: .
          - src: 'cmd/workers/unified/**/*.go'
            dest: .
    - image: gprins/whois
      context: .
      docker:
        dockerfile: cmd/whois/Dockerfile
      sync:
        manual:
          - src: 'internal/**/*.go'
            dest: .
          - src: 'cmd/whois/**/*.go'
            dest: .
manifests:
  helm:
    releases:
      - name: dos
        chartPath: deploy/helm/dos
        valuesFiles:
          - deploy/helm/dos/values-local.yaml
        setValues:
          api.image: gprins/domain-os
          unifiedworker.image: gprins/unified-worker



portForward:
  - resourceType: deployment
    resourceName: dos-api
    port: 8080
    localPort: 8080
  - resourceType: deployment
    resourceName: dos-api
    port: 8081
    localPort: 8081
