apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: jumpingressroute
spec:
  entryPoints:
  - ssh
  routes:
  - match: HostSNI(`*`)
    kind: Rule
    services:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}
