apiVersion: v1
kind: Secret
metadata:
  name: metabase-secret
  labels:
    app: metabase
type: Opaque
stringData:
  MB_DB_USER: {{ .Values.metabase.secret.MB_DB_USER | quote }}
  MB_DB_PASS: {{ .Values.metabase.secret.MB_DB_PASS | quote }}
