apiVersion: v1
kind: Service
metadata:
  name: metabase
  labels:
    app: metabase
spec:
  type: {{ .Values.metabase.service.type }}
  ports:
    - port: {{ .Values.metabase.service.port }}
      targetPort: {{ .Values.metabase.service.port }}
      name: metabase-port
      protocol: TCP
  selector:
    app: metabase
