apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  DB_USER: {{ .Values.db.DB_USER | b64enc | quote }}
  DB_PASS: {{ .Values.db.DB_PASS | b64enc | quote }}

  NEWRELIC_LICENCE_KEY: {{ .Values.newrelic.LICENCE_KEY | b64enc | quote }}
  NEWRELIC_USER_KEY: {{ .Values.newrelic.USER_KEY | b64enc | quote }}

  OPENEXCHANGERATES_APP_ID: {{ .Values.fx.OPENEXCHANGERATES_APP_ID | b64enc | quote }}

  RMQ_USER: {{ .Values.rabbitmq.user | b64enc | quote }}
  RMQ_PASS: {{ .Values.rabbitmq.pass | b64enc | quote }}

  TMPIO_CERT: {{ .Values.temporal.TMPIO_CERT | b64enc | quote }}
  TMPIO_KEY: {{ .Values.temporal.TMPIO_KEY | b64enc | quote }}

  ADMIN_TOKEN: {{ .Values.app.ADMIN_TOKEN | b64enc | quote }}

