apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: api-svc-port
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP