apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  POSTGRES_DB: {{ .Values.db.name }}
  POSTGRES_HOST_AUTH_METHOD: {{ .Values.db.authMethod }} 
  POSTGRES_INITDB_ARGS: {{ .Values.db.initdbArgs }}