apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.db.pass | b64enc | quote }}
  POSTGRES_USER: {{ .Values.db.user | b64enc | quote }}
