apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-consumer
  template:
    metadata:
      labels:
        app: event-consumer
    spec:
      containers:
        - name: event-consumer
          image: {{ .Values.eventConsumer.image }}:{{ .Values.eventConsumer.branch }}
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: kafka-config
          - secretRef:
              name: kafka-secrets

      volumes:
        - name: kafka-client-config
          configMap:
            name: kafka-client-config