apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-client-config
data:
  client.properties: |
    security.protocol=SASL_PLAINTEXT
    sasl.mechanism=SCRAM-SHA-256
    sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required \
      username="user1" \
      password="7LWSPZhWWw";