apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  KAFKA_HOST: {{ .Values.kafka.host | quote }}
  KAFKA_PORT: {{ .Values.kafka.port | quote }}
  KAFKA_TOPIC: {{ .Values.kafka.topic | quote }}
  KAFKA_GROUP: {{ .Values.kafka.group | quote }}
  KAFKA_SECURITY_PROTOCOL: {{ .Values.kafka.securityProtocol | quote }}
  KAFKA_SASL_MECHANISM: {{ .Values.kafka.saslMechanism | quote }}
  KAFKA_SASL_USERNAME: {{ .Values.kafka.saslUsername | quote }}