apiVersion: v1
kind: Secret
metadata:
  name: kafka-secrets
type: Opaque
data:
  KAFKA_SASL_PASSWORD: {{ .Values.kafka.saslPassword | b64enc | quote }}
  KAFKA_SECURITY_PROTOCOL: {{ .Values.kafka.securityProtocol | b64enc | quote }}
  KAFKA_SASL_MECHANISM: {{ .Values.kafka.saslMechanism | b64enc | quote }}
  KAFKA_SASL_USERNAME: {{ .Values.kafka.saslUsername | b64enc | quote }}