apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik
  labels:
    app: traefik
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: web
      protocol: TCP
      port: 80
    - name: websecure
      protocol: TCP
      port: 443
    - name: admin
      protocol: TCP
      port: 8080
  selector:
    app: traefik
