apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
data:
  RMQ_HOST: {{ .Values.rabbitmq.host | b64enc | quote }}
  RMQ_PORT: {{ .Values.rabbitmq.port | b64enc | quote }}
  RMQ_USER: {{ .Values.rabbitmq.user | b64enc | quote }}
  RMQ_PASS: {{ .Values.rabbitmq.pass | b64enc | quote }}
  EVENT_STREAM_TOPIC: {{ .Values.rabbitmq.topic | b64enc | quote }}