apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  GIN_MODE: {{ .Values.gin.GIN_MODE | quote }}
  
  NEW_RELIC_ENABLED: {{ .Values.newrelic.enabled | quote }}
  EVENT_STREAM_ENABLED: {{ .Values.rabbitmq.enabled | quote }}
  EVENT_STREAM_TOPIC: {{ .Values.rabbitmq.topic | quote }}
  
  DB_HOST: {{ .Values.db.DB_HOST | quote }}
  DB_PORT: {{ .Values.db.DB_PORT | quote }}
  DB_NAME: {{ .Values.db.DB_NAME | quote }}
  AUTO_MIGRATE: {{ .Values.db.AUTO_MIGRATE | quote }}

  API_PORT: {{ .Values.app.API_PORT | quote }}
  API_HOST: {{ .Values.app.API_HOST | quote }}
  API_VERSION: {{ .Values.app.API_VERSION | quote }}
  API_NAME: {{ .Values.app.API_NAME | quote }}

  RMQ_HOST: {{ .Values.rabbitmq.host | quote }}
  RMQ_PORT: {{ .Values.rabbitmq.port | quote }}

  TMPIO_HOST_PORT: {{ .Values.temporal.TMPIO_HOST_PORT | quote }}
  TMPIO_NAME_SPACE: {{ .Values.temporal.TMPIO_NAME_SPACE | quote }}
  TMPIO_QUEUE: {{ .Values.temporal.TMPIO_QUEUE | quote }}
  TMPIO_SYNC_QUEUE: {{ .Values.temporal.TMPIO_SYNC_QUEUE | quote }}

  PROMETHEUS_ENABLED: {{ .Values.prometheus.enabled | quote }}
