package rdereport

import (
	"bytes"
	"encoding/xml"
	"errors"
	"fmt"
	"regexp"
	"strings"
	"time"

	"github.com/onasunnymorning/domain-os/internal/application/rdevalidate"
	"github.com/onasunnymorning/domain-os/pkg/domain/entities"
)

// SpecVersion is the pinned specification this adapter targets.
const SpecVersion = "draft-lozano-icann-registry-interfaces-26"

// Namespaces of the emitted documents.
const (
	NSReport       = "urn:ietf:params:xml:ns:rdeReport-1.0"
	NSHeader       = "urn:ietf:params:xml:ns:rdeHeader-1.0" // == entities.RDE_HEADER_URI
	NSNotification = "urn:ietf:params:xml:ns:rdeNotification-1.0"
	NSIIRDEA       = "urn:ietf:params:xml:ns:iirdea-1.0"
)

// reportVersion and notificationVersion "MUST be 1" (draft-26 §1.4.2, §1.4.3).
const (
	reportVersion       = 1
	notificationVersion = 1
)

// reportedObjectURIs are the object namespaces the header always counts.
// rdeDomain must always be present: ICANN rejects a DVPN whose header lacks
// the domain count (draft-26 Table 2, result 2203).
var reportedObjectURIs = []string{
	entities.DOMAIN_URI, entities.HOST_URI, entities.CONTACT_URI,
	entities.REGISTRAR_URI, entities.IDN_URI, entities.NNDN_URI,
}

var depositIDRe = regexp.MustCompile(`^\w{1,13}$`)

// Report is the <rdeReport:report> element (draft-26 §9.2).
type Report struct {
	XMLName     xml.Name `xml:"rdeReport:report"`
	XMLNSReport string   `xml:"xmlns:rdeReport,attr,omitempty"`
	XMLNSHeader string   `xml:"xmlns:rdeHeader,attr,omitempty"`

	ID              string `xml:"rdeReport:id"`
	Version         int    `xml:"rdeReport:version"`
	RydeSpecEscrow  string `xml:"rdeReport:rydeSpecEscrow"`
	RydeSpecMapping string `xml:"rdeReport:rydeSpecMapping,omitempty"`
	Resend          int    `xml:"rdeReport:resend"`
	CrDate          string `xml:"rdeReport:crDate"`
	Kind            string `xml:"rdeReport:kind"`
	Watermark       string `xml:"rdeReport:watermark"`
	Header          Header `xml:"rdeHeader:header"`
}

// Header is the <rdeHeader:header> element (RFC 9022 §8), generated by the
// Data Escrow Agent from what it actually observed in the deposit.
type Header struct {
	TLD   string  `xml:"rdeHeader:tld"`
	Count []Count `xml:"rdeHeader:count"`
}

// Count is one <rdeHeader:count uri="...">n</rdeHeader:count>.
type Count struct {
	URI string `xml:"uri,attr"`
	N   int    `xml:",chardata"`
}

// Hints are deposit facts known from the intake context (typically parsed
// from the ICANN file-name convention) and used only when the deposit could
// not be opened far enough to read them itself.
type Hints struct {
	DepositID string
	Kind      string
	Watermark time.Time
}

// Params are the inputs to both builders.
type Params struct {
	DEAName     string
	Result      rdevalidate.Result
	BoundTLD    string
	ReceivedAt  time.Time
	ValidatedAt time.Time
	// LastFullDate is the watermark date of the most recent FULL deposit this
	// agent validated for the TLD, if any. Stage 1 does not track it; leave nil.
	LastFullDate *time.Time
	Hints        Hints
}

// ErrNoNotificationForOutcome is returned when the outcome carries no
// notification (ERROR: the service could not decide).
var ErrNoNotificationForOutcome = errors.New("rdereport: no notification is emitted for this outcome")

// BuildReport assembles the report from the run result. Where the deposit
// could not be opened far enough to supply a field, intake hints are used,
// then deterministic fallbacks, so a DVFN for an undecryptable artifact is
// still schema-valid and still identifies the artifact.
func BuildReport(p Params) (*Report, error) {
	tld, err := entities.NormalizeEscrowTLD(p.BoundTLD)
	if err != nil {
		return nil, fmt.Errorf("rdereport: bound TLD: %w", err)
	}
	if p.ReceivedAt.IsZero() {
		return nil, errors.New("rdereport: ReceivedAt is required")
	}
	dep := p.Result.Deposit

	id := dep.ID
	if !depositIDRe.MatchString(id) {
		id = p.Hints.DepositID
	}
	if !depositIDRe.MatchString(id) {
		// The artifact digest is the one identifier we always have.
		id = strings.ToUpper(firstN(p.Result.Digests.ArtifactSHA256, 13))
	}
	if id == "" {
		return nil, errors.New("rdereport: no deposit identifier is available")
	}

	kind := dep.Kind
	if !isKind(kind) {
		kind = strings.ToUpper(p.Hints.Kind)
	}
	if !isKind(kind) {
		kind = entities.RDEReportTypeFULL
	}

	watermark := dep.Watermark
	if watermark.IsZero() {
		watermark = p.Hints.Watermark
	}
	if watermark.IsZero() {
		watermark = p.ReceivedAt
	}

	crDate := p.Result.Decryption.LiteralTime
	if crDate.IsZero() {
		crDate = p.Result.Signature.SignedAt
	}
	if crDate.IsZero() {
		crDate = p.ReceivedAt
	}

	counts := make([]Count, 0, len(reportedObjectURIs))
	for _, uri := range reportedObjectURIs {
		counts = append(counts, Count{URI: uri, N: dep.Observed[uri]})
	}

	return &Report{
		ID:              id,
		Version:         reportVersion,
		RydeSpecEscrow:  entities.RYDE_ESCROW_RFC,
		RydeSpecMapping: entities.RYDE_MAPPING_RFC,
		Resend:          dep.Resend,
		CrDate:          fmtDateTime(crDate),
		Kind:            kind,
		Watermark:       fmtDateTime(watermark),
		Header:          Header{TLD: tld, Count: counts},
	}, nil
}

// Marshal renders a standalone report document.
func (r *Report) Marshal() ([]byte, error) {
	cp := *r
	cp.XMLNSReport = NSReport
	cp.XMLNSHeader = NSHeader
	return marshalDoc(&cp)
}

// WatermarkDate returns the report's watermark as a date (repDate).
func (r *Report) WatermarkDate() (string, error) {
	t, err := time.Parse(time.RFC3339, r.Watermark)
	if err != nil {
		return "", err
	}
	return fmtDate(t), nil
}

func marshalDoc(v any) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(xml.Header)
	enc := xml.NewEncoder(&buf)
	enc.Indent("", "  ")
	if err := enc.Encode(v); err != nil {
		return nil, err
	}
	if err := enc.Flush(); err != nil {
		return nil, err
	}
	buf.WriteByte('\n')
	return buf.Bytes(), nil
}

func fmtDateTime(t time.Time) string { return t.UTC().Format("2006-01-02T15:04:05Z") }
func fmtDate(t time.Time) string     { return t.UTC().Format("2006-01-02") }

func isKind(k string) bool {
	switch k {
	case entities.RDEReportTypeFULL, entities.RDEReportTypeDIFF, entities.RDEReportTypeINCR:
		return true
	}
	return false
}

func firstN(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n]
}

// rydeFileNameRe matches the ICANN deposit file-name convention
// <tld>_<YYYY-MM-DD>_<full|diff|incr>_S<seq>_R<rev>.ryde (case-insensitive).
var rydeFileNameRe = regexp.MustCompile(`(?i)^([a-z0-9-]+)_(\d{4}-\d{2}-\d{2})_(full|diff|incr)_s(\d+)_r(\d+)\.ryde$`)

// ParseRydeFileName extracts intake hints from a conventionally named
// deposit. The base name only is inspected; it is never echoed anywhere.
func ParseRydeFileName(name string) (Hints, bool) {
	base := name
	if i := strings.LastIndexAny(base, "/\\"); i >= 0 {
		base = base[i+1:]
	}
	m := rydeFileNameRe.FindStringSubmatch(base)
	if m == nil {
		return Hints{}, false
	}
	wm, err := time.Parse("2006-01-02", m[2])
	if err != nil {
		return Hints{}, false
	}
	id := strings.ReplaceAll(m[2], "-", "") + fmt.Sprintf("%03s", m[4])
	if len(id) > 13 {
		id = id[:13]
	}
	return Hints{DepositID: id, Kind: strings.ToUpper(m[3]), Watermark: wm.UTC()}, true
}
