apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-admin-api
  labels:
    app: admin-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-api
  template:
    metadata:
      labels:
        app: admin-api
    spec:
      containers:
        - name: admin-api
          image: "geapex/domain-os:{{ .Values.branch }}"
          ports:
            - containerPort: {{ .Values.api.port | int }}
          env:
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: ENV
            - name: GIN_MODE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: GIN_MODE
            - name: OPENEXCHANGERATES_APP_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: OPENEXCHANGERATES_APP_ID
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: DB_NAME
            - name: API_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: API_PORT
            - name: API_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: API_HOST
            - name: API_VERSION
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: API_VERSION
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: DB_PASS
          livenessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.api.port | int }}
            initialDelaySeconds: 10
            periodSeconds: 3
            failureThreshold: 5
