apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-admin-api
spec:
  selector:
    app: admin-api
  ports:
    - protocol: TCP
      port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
  type: LoadBalancer
