apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.secretName }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  DB_USER: {{ .Values.DB_USER | b64enc | quote }}
  DB_PASS: {{ .Values.DB_PASS | b64enc | quote }}

  NEWRELIC_LICENCE_KEY: {{ .Values.NEWRELIC_LICENCE_KEY | b64enc | quote }}
  NEWRELIC_USER_KEY: {{ .Values.NEWRELIC_USER_KEY | b64enc | quote }}

  OPENEXCHANGERATES_APP_ID: {{ .Values.OPENEXCHANGERATES_APP_ID | b64enc | quote }}

  RMQ_USER: {{ .Values.RMQ_USER | b64enc | quote }}
  RMQ_PASS: {{ .Values.RMQ_PASS | b64enc | quote }}

  TMPIO_CERT: {{ .Values.TMPIO_CERT | b64enc | quote }}
  TMPIO_KEY: {{ .Values.TMPIO_KEY | b64enc | quote }}

  API_TOKEN: {{ .Values.API_TOKEN | b64enc | quote }}
