apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: "{{ .Values.service.name }}-port"
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP