apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroutemetabase
  namespace: geoffdev
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`dos.dev.geoff.it`)
    kind: Rule
    services:
    - name: metabase
      port: 3000
  tls:
    certResolver: myresolver

# ---

# apiVersion: traefik.io/v1alpha1
# kind: IngressRoute
# metadata:
#   name: ingressrouteapi
#   namespace: geoffdev
# spec:
#   entryPoints:
#   - web
#   routes:
#   - match: Host(`ingress.geoff.it`)
#     kind: Rule
#     services:
#     - name: dos-internal-svc
#       port: 8080
