apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik
  labels:
    app: traefik
spec:
  type: LoadBalancer
  ports:
  - name: ssh
    protocol: TCP
    port: 2222
  - name: web
    protocol: TCP
    port: 80
  - name: dns
    protocol: UDP
    port: 53
  - name: websecure
    protocol: TCP
    port: 443
  - name: admin
    protocol: TCP
    port: 8080
  selector:
    app: traefik
