package config

import (
	"strings"
	"time"
)

// Contract is the deployment interface between the app repo and infra repos.
// It is generated by cmd/tools/gencontract — never edit deploy/contract.json by hand.
type Contract struct {
	SchemaVersion  string                     `json:"schema_version"`
	Generated      string                     `json:"generated"`
	Services       map[string]ServiceContract `json:"services"`
	Infrastructure []InfraComponent           `json:"infrastructure"`
}

// ServiceContract describes a single deployable service.
type ServiceContract struct {
	Image    string `json:"image"`
	Port     int    `json:"port,omitempty"`
	Protocol string `json:"protocol,omitempty"`
	// EnvInjection is "runtime" when env vars are read by the running container,
	// or "build" when they must be supplied as docker build args. Infra repos
	// must not pass "build" vars as container env, or vice versa.
	EnvInjection string          `json:"env_injection"`
	HealthCheck  *HealthCheck    `json:"health_check,omitempty"`
	EnvVars      ContractEnvVars `json:"env_vars"`
}

// HealthCheck describes how to check if a service is healthy.
type HealthCheck struct {
	Type string `json:"type"`           // "http", "tcp", or "temporal-heartbeat"
	Path string `json:"path,omitempty"` // HTTP path (e.g. "/ping")
	Port int    `json:"port,omitempty"` // Port to check
}

// ContractEnvVars groups environment variables by requirement level.
type ContractEnvVars struct {
	Required []ContractEnvVar `json:"required"`
	Optional []ContractEnvVar `json:"optional"`
}

// ContractEnvVar describes a single environment variable in the contract.
type ContractEnvVar struct {
	Name    string `json:"name"`
	Default string `json:"default,omitempty"`
	Secret  bool   `json:"secret,omitempty"`
	// RequiredWhen is set when the variable is required only under a condition,
	// in the form "OTHER_VAR=value". Such vars appear under `optional`.
	RequiredWhen string `json:"required_when,omitempty"`
	Description  string `json:"description"`
}

// InfraComponent describes a shared infrastructure dependency.
// Port is omitted when the component has no single well-known port — S3 is
// reached at whatever STORAGE_ENDPOINT names, on 443 for AWS/R2 and 9000 for
// a local MinIO, so publishing either number would mislead.
type InfraComponent struct {
	Name   string   `json:"name"`
	Port   int      `json:"port,omitempty"`
	UsedBy []string `json:"used_by"`
}

// serviceMeta holds the static metadata for each deployable service.
// This is the single place where image names, ports, and health checks are defined.
type serviceMeta struct {
	ContractName string       // Key in the contract JSON (e.g. "admin-api")
	Image        string       // Docker Hub image name
	Port         int          // Exposed port (0 = none)
	Protocol     string       // "http", "tls", "tcp", or ""
	HealthCheck  *HealthCheck // nil if no health check
	Services     []Service    // Which Service constants map to this deployable
	BuildTime    bool         // If true, env vars must be supplied as docker build args rather than container env
}

// serviceMetaRegistry maps Service constants to their deployable service metadata.
// When adding a new service, add an entry here.
var serviceMetaRegistry = []serviceMeta{
	{
		ContractName: "admin-api",
		Image:        "gprins/domain-os-api",
		Port:         8080,
		Protocol:     "http",
		HealthCheck:  &HealthCheck{Type: "http", Path: "/ping", Port: 8080},
		Services:     []Service{ServiceAPI},
	},
	{
		ContractName: "unified-worker",
		Image:        "gprins/domain-os-worker",
		Protocol:     "",
		HealthCheck:  &HealthCheck{Type: "temporal-heartbeat"},
		Services:     []Service{ServiceWorker},
	},
	{
		ContractName: "epp-server",
		Image:        "gprins/domain-os-epp",
		Port:         700,
		Protocol:     "tls",
		HealthCheck:  &HealthCheck{Type: "tcp", Port: 700},
		Services:     []Service{ServiceEPP},
	},
	{
		ContractName: "whois",
		Image:        "gprins/domain-os-whois",
		Port:         43,
		Protocol:     "tcp",
		HealthCheck:  &HealthCheck{Type: "tcp", Port: 43},
		Services:     []Service{ServiceWhois},
	},
	{
		ContractName: "mcp-server",
		Image:        "gprins/domain-os-mcp",
		Port:         3001,
		Protocol:     "http",
		HealthCheck:  &HealthCheck{Type: "http", Path: "/healthz", Port: 3001},
		Services:     []Service{ServiceMCP},
	},
	{
		ContractName: "frontend",
		Image:        "gprins/domain-os-frontend",
		Port:         3000,
		Protocol:     "http",
		// Unauthenticated route handler; GET / would work but sits behind the
		// Auth0 gate and renders the full React shell on every ALB probe.
		HealthCheck: &HealthCheck{Type: "http", Path: "/api/health", Port: 3000},
		Services:    []Service{ServiceFrontend},
		// NEXT_PUBLIC_* vars are injected at container start by next-runtime-env,
		// so the image is environment-agnostic and infra sets plain container env.
		// See docs/adr/0001-runtime-env-configuration.md
		BuildTime: false,
	},
}

// infraComponentSpec declares a shared infrastructure component. UsedBy is not
// listed here: it is derived from the env registry, so the two cannot drift.
// A service uses the component iff it declares any of ProbeVars.
type infraComponentSpec struct {
	Name      string
	Port      int      // 0 = no single well-known port
	ProbeVars []string // declaring any of these means "uses this component"
}

var infraSpecs = []infraComponentSpec{
	{Name: "postgresql", Port: 5432, ProbeVars: []string{"DATABASE_URL", "DB_HOST"}},
	{Name: "redis", Port: 6379, ProbeVars: []string{"REDIS_HOST"}},
	{Name: "temporal", Port: 7233, ProbeVars: []string{"TEMPORAL_HOST_PORT"}},
	// No port: the endpoint is whatever STORAGE_ENDPOINT names (443 for AWS/R2,
	// 9000 for a local MinIO). Publishing one of those would mislead consumers.
	{Name: "s3", Port: 0, ProbeVars: []string{"STORAGE_ENDPOINT"}},
}

// nameLooksSecret reports whether an env var name matches the legacy substring
// heuristic. It no longer decides the contract — EnvVar.Secret does — but
// TestSecretsAreExplicit uses it as a lower bound, so a newly added var whose
// name screams "credential" cannot ship with Secret unset.
//
// The heuristic is kept only for that guard because it fails in the unsafe
// direction: "PASSWORD" is not a substring of "DB_PASS", and "DATABASE_URL"
// embeds a password while matching nothing at all.
func nameLooksSecret(name string) bool {
	if strings.HasPrefix(name, "NEXT_PUBLIC_") {
		return false
	}
	upper := strings.ToUpper(name)
	for _, pattern := range []string{"SECRET", "PASSWORD", "TOKEN", "CERT", "KEY", "LICENSE"} {
		if strings.Contains(upper, pattern) {
			return true
		}
	}
	return false
}

// isSecret reports whether a variable is credential material.
//
// NEXT_PUBLIC_* values are served to every browser in window.__ENV, so they can
// never be secret regardless of how they are declared. Everything else is taken
// verbatim from the registry's explicit Secret field.
func isSecret(v EnvVar) bool {
	if strings.HasPrefix(v.Name, "NEXT_PUBLIC_") {
		return false
	}
	return v.Secret
}

// GenerateContract builds the deployment contract from the env var registry
// and service metadata. It describes the deployment interface (images, ports,
// env vars, health checks), which is version-independent — the app version
// travels on the image tag (a git-tag-driven release), not in the contract.
func GenerateContract() (*Contract, error) {
	// Build a lookup: Service -> contract name
	serviceToContract := make(map[Service]string)
	for _, meta := range serviceMetaRegistry {
		for _, svc := range meta.Services {
			serviceToContract[svc] = meta.ContractName
		}
	}

	// Group env vars by contract service name
	type envGroup struct {
		required []ContractEnvVar
		optional []ContractEnvVar
	}
	groups := make(map[string]*envGroup)
	for _, meta := range serviceMetaRegistry {
		groups[meta.ContractName] = &envGroup{}
	}

	for _, envVar := range Registry {
		// Skip CLI-only and runtime-detection vars — not relevant for deployment
		if len(envVar.Services) == 1 && envVar.Services[0] == ServiceCLI {
			continue
		}
		if envVar.Name == "LAMBDA_TASK_ROOT" || envVar.Name == "KUBERNETES_SERVICE_HOST" {
			continue
		}

		// Determine which contract services use this var
		contractServices := make(map[string]bool)
		for _, svc := range envVar.Services {
			if svc == ServiceCLI {
				continue // Skip CLI service mappings
			}
			if contractName, ok := serviceToContract[svc]; ok {
				contractServices[contractName] = true
			}
		}

		contractVar := ContractEnvVar{
			Name:         envVar.Name,
			Default:      envVar.Default,
			Secret:       isSecret(envVar),
			RequiredWhen: envVar.RequiredWhen,
			Description:  envVar.Description,
		}

		for contractName := range contractServices {
			g := groups[contractName]
			if g == nil {
				continue
			}
			if envVar.Required {
				g.required = append(g.required, contractVar)
			} else {
				g.optional = append(g.optional, contractVar)
			}
		}
	}

	// whois and mcp-server declare ServiceWhois / ServiceMCP on the DB_* vars they
	// read, so no special-casing is needed here any more.

	// Build the contract
	services := make(map[string]ServiceContract, len(serviceMetaRegistry))
	for _, meta := range serviceMetaRegistry {
		g := groups[meta.ContractName]
		envInjection := "runtime"
		if meta.BuildTime {
			envInjection = "build"
		}
		svc := ServiceContract{
			Image:        meta.Image,
			Port:         meta.Port,
			Protocol:     meta.Protocol,
			EnvInjection: envInjection,
			HealthCheck:  meta.HealthCheck,
			EnvVars: ContractEnvVars{
				Required: g.required,
				Optional: g.optional,
			},
		}
		// Ensure empty slices serialize as [] not null
		if svc.EnvVars.Required == nil {
			svc.EnvVars.Required = []ContractEnvVar{}
		}
		if svc.EnvVars.Optional == nil {
			svc.EnvVars.Optional = []ContractEnvVar{}
		}
		services[meta.ContractName] = svc
	}

	contract := &Contract{
		SchemaVersion:  "3",
		Generated:      time.Now().UTC().Format(time.RFC3339),
		Services:       services,
		Infrastructure: buildInfrastructure(serviceToContract),
	}

	return contract, nil
}

// buildInfrastructure derives each component's used_by from the env registry: a
// service uses a component iff it declares one of the component's probe vars.
// Deriving it means infra and env can no longer disagree about, say, whether
// mcp-server talks to Postgres.
func buildInfrastructure(serviceToContract map[Service]string) []InfraComponent {
	// contract service name -> set of env var names it declares
	declared := make(map[string]map[string]bool)
	for _, envVar := range Registry {
		for _, svc := range envVar.Services {
			if svc == ServiceCLI {
				continue
			}
			name, ok := serviceToContract[svc]
			if !ok {
				continue
			}
			if declared[name] == nil {
				declared[name] = make(map[string]bool)
			}
			declared[name][envVar.Name] = true
		}
	}

	// Stable output order: follow serviceMetaRegistry, not Go's map iteration.
	orderedServices := make([]string, 0, len(serviceMetaRegistry))
	for _, meta := range serviceMetaRegistry {
		orderedServices = append(orderedServices, meta.ContractName)
	}

	components := make([]InfraComponent, 0, len(infraSpecs))
	for _, spec := range infraSpecs {
		usedBy := []string{}
		for _, svcName := range orderedServices {
			for _, probe := range spec.ProbeVars {
				if declared[svcName][probe] {
					usedBy = append(usedBy, svcName)
					break
				}
			}
		}
		components = append(components, InfraComponent{
			Name:   spec.Name,
			Port:   spec.Port,
			UsedBy: usedBy,
		})
	}
	return components
}
