package config

import (
	"os"
	"strings"
	"time"
)

// Contract is the deployment interface between the app repo and infra repos.
// It is generated by cmd/tools/gencontract — never edit deploy/contract.json by hand.
type Contract struct {
	SchemaVersion  string                     `json:"schema_version"`
	AppVersion     string                     `json:"app_version"`
	Generated      string                     `json:"generated"`
	Services       map[string]ServiceContract `json:"services"`
	Infrastructure []InfraComponent           `json:"infrastructure"`
}

// ServiceContract describes a single deployable service.
type ServiceContract struct {
	Image       string          `json:"image"`
	Port        int             `json:"port,omitempty"`
	Protocol    string          `json:"protocol,omitempty"`
	HealthCheck *HealthCheck    `json:"health_check,omitempty"`
	EnvVars     ContractEnvVars `json:"env_vars"`
}

// HealthCheck describes how to check if a service is healthy.
type HealthCheck struct {
	Type string `json:"type"`           // "http", "tcp", or "temporal-heartbeat"
	Path string `json:"path,omitempty"` // HTTP path (e.g. "/ping")
	Port int    `json:"port,omitempty"` // Port to check
}

// ContractEnvVars groups environment variables by requirement level.
type ContractEnvVars struct {
	Required []ContractEnvVar `json:"required"`
	Optional []ContractEnvVar `json:"optional"`
}

// ContractEnvVar describes a single environment variable in the contract.
type ContractEnvVar struct {
	Name        string `json:"name"`
	Default     string `json:"default,omitempty"`
	Secret      bool   `json:"secret,omitempty"`
	Description string `json:"description"`
}

// InfraComponent describes a shared infrastructure dependency.
type InfraComponent struct {
	Name   string   `json:"name"`
	Port   int      `json:"port"`
	UsedBy []string `json:"used_by"`
}

// serviceMeta holds the static metadata for each deployable service.
// This is the single place where image names, ports, and health checks are defined.
type serviceMeta struct {
	ContractName string       // Key in the contract JSON (e.g. "admin-api")
	Image        string       // Docker Hub image name
	Port         int          // Exposed port (0 = none)
	Protocol     string       // "http", "tls", "tcp", or ""
	HealthCheck  *HealthCheck // nil if no health check
	Services     []Service    // Which Service constants map to this deployable
	BuildTime    bool         // If true, env vars are build-time args (frontend)
}

// serviceMetaRegistry maps Service constants to their deployable service metadata.
// When adding a new service, add an entry here.
var serviceMetaRegistry = []serviceMeta{
	{
		ContractName: "admin-api",
		Image:        "geapex/domain-os",
		Port:         8080,
		Protocol:     "http",
		HealthCheck:  &HealthCheck{Type: "http", Path: "/ping", Port: 8080},
		Services:     []Service{ServiceAPI},
	},
	{
		ContractName: "unified-worker",
		Image:        "geapex/unified-worker",
		Protocol:     "",
		HealthCheck:  &HealthCheck{Type: "temporal-heartbeat"},
		Services:     []Service{ServiceWorker},
	},
	{
		ContractName: "epp-server",
		Image:        "geapex/epp-server",
		Port:         700,
		Protocol:     "tls",
		HealthCheck:  &HealthCheck{Type: "tcp", Port: 700},
		Services:     []Service{ServiceEPP},
	},
	{
		ContractName: "whois",
		Image:        "geapex/whois",
		Port:         43,
		Protocol:     "tcp",
		HealthCheck:  nil,
		Services:     []Service{},
	},
	{
		ContractName: "mcp-server",
		Image:        "geapex/mcp-server",
		Port:         3001,
		Protocol:     "http",
		HealthCheck:  &HealthCheck{Type: "http", Path: "/healthz", Port: 3001},
		Services:     []Service{ServiceMCP},
	},
	{
		ContractName: "frontend",
		Image:        "geapex/domain-os-frontend",
		Port:         3000,
		Protocol:     "http",
		HealthCheck:  nil,
		Services:     []Service{ServiceFrontend},
		BuildTime:    true,
	},
}

// infraRegistry defines the shared infrastructure components and which services use them.
var infraRegistry = []InfraComponent{
	{Name: "postgresql", Port: 5432, UsedBy: []string{"admin-api", "unified-worker", "whois", "mcp-server"}},
	{Name: "redis", Port: 6379, UsedBy: []string{"epp-server"}},
	{Name: "temporal", Port: 7233, UsedBy: []string{"admin-api", "unified-worker"}},
	{Name: "s3", Port: 9000, UsedBy: []string{"admin-api", "unified-worker"}},
}

// secretPatterns are substrings in env var names that indicate secrets.
var secretPatterns = []string{"SECRET", "PASSWORD", "TOKEN", "CERT", "KEY", "LICENSE"}

// isSecret returns true if the env var name looks like a secret.
func isSecret(name string) bool {
	// Check if it's a NEXT_PUBLIC_ var — these are never secrets (baked into client JS)
	if strings.HasPrefix(name, "NEXT_PUBLIC_") {
		return false
	}
	upper := strings.ToUpper(name)
	for _, pattern := range secretPatterns {
		if strings.Contains(upper, pattern) {
			return true
		}
	}
	return false
}

// GenerateContract builds the deployment contract from the env var registry
// and service metadata. The versionFilePath should point to the VERSION file.
func GenerateContract(versionFilePath string) (*Contract, error) {
	// Read version
	versionBytes, err := os.ReadFile(versionFilePath)
	if err != nil {
		return nil, err
	}
	version := strings.TrimSpace(string(versionBytes))

	// Build a lookup: Service -> contract name
	serviceToContract := make(map[Service]string)
	for _, meta := range serviceMetaRegistry {
		for _, svc := range meta.Services {
			serviceToContract[svc] = meta.ContractName
		}
	}

	// Group env vars by contract service name
	type envGroup struct {
		required []ContractEnvVar
		optional []ContractEnvVar
	}
	groups := make(map[string]*envGroup)
	for _, meta := range serviceMetaRegistry {
		groups[meta.ContractName] = &envGroup{}
	}

	for _, envVar := range Registry {
		// Skip CLI-only and runtime-detection vars — not relevant for deployment
		if len(envVar.Services) == 1 && envVar.Services[0] == ServiceCLI {
			continue
		}
		if envVar.Name == "LAMBDA_TASK_ROOT" || envVar.Name == "KUBERNETES_SERVICE_HOST" {
			continue
		}

		// Determine which contract services use this var
		contractServices := make(map[string]bool)
		for _, svc := range envVar.Services {
			if svc == ServiceCLI {
				continue // Skip CLI service mappings
			}
			if contractName, ok := serviceToContract[svc]; ok {
				contractServices[contractName] = true
			}
		}

		// WHOIS uses DB vars directly but has no Service constant in the registry
		// (its env vars are under ServiceAPI/ServiceWorker). Handle this via the
		// service meta's Services list — WHOIS has an empty Services slice, so
		// DB vars won't auto-map. We handle WHOIS separately below.

		contractVar := ContractEnvVar{
			Name:        envVar.Name,
			Default:     envVar.Default,
			Secret:      isSecret(envVar.Name),
			Description: envVar.Description,
		}

		for contractName := range contractServices {
			g := groups[contractName]
			if g == nil {
				continue
			}
			if envVar.Required {
				g.required = append(g.required, contractVar)
			} else {
				g.optional = append(g.optional, contractVar)
			}
		}
	}

	// WHOIS reads DB_* vars directly — add them manually since WHOIS
	// has no Service constant in the env registry (it shares the DB vars
	// with ServiceAPI/ServiceWorker but needs its own copy in the contract).
	whoisDBVars := []string{"DB_USER", "DB_PASS", "DB_HOST", "DB_PORT", "DB_NAME", "DB_SSLMODE"}
	regMap := RegistryMap()
	for _, name := range whoisDBVars {
		if envVar, ok := regMap[name]; ok {
			contractVar := ContractEnvVar{
				Name:        envVar.Name,
				Default:     envVar.Default,
				Secret:      isSecret(envVar.Name),
				Description: envVar.Description,
			}
			groups["whois"].optional = append(groups["whois"].optional, contractVar)
		}
	}

	// Build the contract
	services := make(map[string]ServiceContract, len(serviceMetaRegistry))
	for _, meta := range serviceMetaRegistry {
		g := groups[meta.ContractName]
		svc := ServiceContract{
			Image:       meta.Image,
			Port:        meta.Port,
			Protocol:    meta.Protocol,
			HealthCheck: meta.HealthCheck,
			EnvVars: ContractEnvVars{
				Required: g.required,
				Optional: g.optional,
			},
		}
		// Ensure empty slices serialize as [] not null
		if svc.EnvVars.Required == nil {
			svc.EnvVars.Required = []ContractEnvVar{}
		}
		if svc.EnvVars.Optional == nil {
			svc.EnvVars.Optional = []ContractEnvVar{}
		}
		services[meta.ContractName] = svc
	}

	contract := &Contract{
		SchemaVersion:  "1",
		AppVersion:     version,
		Generated:      time.Now().UTC().Format(time.RFC3339),
		Services:       services,
		Infrastructure: infraRegistry,
	}

	return contract, nil
}
