apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-epp-client
  labels:
    app: epp-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: epp-client
  template:
    metadata:
      labels:
        app: epp-client
    spec:
      containers:
        - name: epp-client
          image: geapex/epp-client-api:latest
          ports:
            - containerPort: 8700
        