apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: epp-client
  ports:
    - protocol: TCP
      port: 8700
      targetPort: 8700
  type: LoadBalancer
